### ISSUE TITLE
Crash when starting

### ISSUE THREAD

**Issue by cubuzz** [GDquest/BPSProxy#5]
EDIT by @NathanLovato: there is an issue with the path to the video files, it may have to do with spaces or something like that. The string gets split into several command line arguments instead of staying as one path.

```
» Creating directories if necessary...

» Checking for existing proxies...
100%|█████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 12.08files/s]

» Processing...
  0%|                                                                                         | 0/4 [00:00<?, ?files/s]Traceback (most recent call last):
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cubuzz\AppData\Local\Programs\Python\Python38-32\Scripts\bpsproxy.exe\__main__.py", line 9, in <module>
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\site-packages\bpsproxy\__main__.py", line 157, in main
    call(C, clargs, cmds=cmds, **kwargs)
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\site-packages\bpsproxy\call.py", line 95, in call
    return [p.stdout for p in ps]
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\site-packages\bpsproxy\call.py", line 95, in <listcomp>
    return [p.stdout for p in ps]
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\site-packages\bpsproxy\call.py", line 91, in <lambda>
    map(lambda cmd: sp.run(cmd[1], **kwargs_s), cmds[1]),
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-hwaccel', 'auto', '-y', '-v', 'quiet', '-stats', '-i', 'F:\\Elgato Media\\Tom Clancys', 'Rainbow', 'Six', 'SiegeTom', 'Clancys Rainbow Six  Siege 2019.10.21 - 21.08.20.01.mp4', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=ceil(iw*0.25/2)*2:ceil(ih*0.25/2)*2', '-c:v', 'libx264', '-crf', '25', '-preset', 'faster', '-tune', 'fastdecode', 'F:\\Elgato Media\\Tom Clancys', 'Rainbow', 'Six', 'SiegeBL_proxyTom', 'Clancys Rainbow Six  Siege 2019.10.21 - 21.08.20.01.mp4\\proxy_25.avi']' returned non-zero exit status 1.
  0%|                                                                                         | 0/4 [00:00<?, ?files/s]
```

**Comment by cubuzz** [comment]
Verbose output:
```
INFO:BPS:WORKING-DIRECTORY :: F:\Elgato Media\Tom Clancy's Rainbow Six  Siege
INFO:BPS:PRESET :: mp4
INFO:BPS:SIZES :: [25]

» Creating directories if necessary...
INFO:BPS:Directory @ F:\Elgato Media\Tom Clancy's Rainbow Six  Siege\BL_proxy\Tom Clancy's Rainbow Six  Siege 2019.10.21 - 21.08.20.01.mp4
INFO:BPS:Directory @ F:\Elgato Media\Tom Clancy's Rainbow Six  Siege\BL_proxy\Tom Clancy's Rainbow Six  Siege 2019.10.22 - 11.15.51.01.mp4
INFO:BPS:Directory @ F:\Elgato Media\Tom Clancy's Rainbow Six  Siege\BL_proxy\Tom Clancy's Rainbow Six  Siege 2019.10.22 - 11.30.41.03.DVR.mp4
INFO:BPS:Directory @ F:\Elgato Media\Tom Clancy's Rainbow Six  Siege\BL_proxy\Tom Clancy's Rainbow Six  Siege 2019.10.22 - 11.41.04.04.DVR.mp4

» Checking for existing proxies...
DEBUG:BPS:CALL :: ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=noprint_wrappers=1:nokey=1 F:\Elgato Media\Tom Clancys Rainbow Six SiegeTom Clancys Rainbow Six  Siege 2019.10.21 - 21.08.20.01.mp4 && ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=noprint_wrappers=1:nokey=1 F:\Elgato Media\Tom Clancys Rainbow Six SiegeBL_proxyTom Clancys Rainbow Six  Siege 2019.10.21 - 21.08.20.01.mp4\proxy_25.avi
DEBUG:BPS:CALL :: ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=noprint_wrappers=1:nokey=1 F:\Elgato Media\Tom Clancys Rainbow Six SiegeTom Clancys Rainbow Six  Siege 2019.10.22 - 11.15.51.01.mp4 && ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=noprint_wrappers=1:nokey=1 F:\Elgato Media\Tom Clancys Rainbow Six SiegeBL_proxyTom Clancys Rainbow Six  Siege 2019.10.22 - 11.15.51.01.mp4\proxy_25.avi
DEBUG:BPS:CALL :: ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=noprint_wrappers=1:nokey=1 F:\Elgato Media\Tom Clancys Rainbow Six SiegeTom Clancys Rainbow Six  Siege 2019.10.22 - 11.30.41.03.DVR.mp4 && ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=noprint_wrappers=1:nokey=1 F:\Elgato Media\Tom Clancys Rainbow Six SiegeBL_proxyTom Clancys Rainbow Six  Siege 2019.10.22 - 11.30.41.03.DVR.mp4\proxy_25.avi
DEBUG:BPS:CALL :: ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=noprint_wrappers=1:nokey=1 F:\Elgato Media\Tom Clancys Rainbow Six SiegeTom Clancys Rainbow Six  Siege 2019.10.22 - 11.41.04.04.DVR.mp4 && ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=noprint_wrappers=1:nokey=1 F:\Elgato Media\Tom Clancys Rainbow Six SiegeBL_proxyTom Clancys Rainbow Six  Siege 2019.10.22 - 11.41.04.04.DVR.mp4\proxy_25.avi
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 11.73files/s]

» Processing...
DEBUG:BPS:CALL :: ['ffmpeg', '-hwaccel', 'auto', '-y', '-v', 'quiet', '-stats', '-i', 'F:\\Elgato Media\\Tom Clancys', 'Rainbow', 'Six', 'SiegeTom', 'Clancys Rainbow Six  Siege 2019.10.21 - 21.08.20.01.mp4', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=ceil(iw*0.25/2)*2:ceil(ih*0.25/2)*2', '-c:v', 'libx264', '-crf', '25', '-preset', 'faster', '-tune', 'fastdecode', 'F:\\Elgato Media\\Tom Clancys', 'Rainbow', 'Six', 'SiegeBL_proxyTom', 'Clancys Rainbow Six  Siege 2019.10.21 - 21.08.20.01.mp4\\proxy_25.avi']
DEBUG:BPS:CALL :: ['ffmpeg', '-hwaccel', 'auto', '-y', '-v', 'quiet', '-stats', '-i', 'F:\\Elgato Media\\Tom Clancys', 'Rainbow', 'Six', 'SiegeTom', 'Clancys Rainbow Six  Siege 2019.10.22 - 11.15.51.01.mp4', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=ceil(iw*0.25/2)*2:ceil(ih*0.25/2)*2', '-c:v', 'libx264', '-crf', '25', '-preset', 'faster', '-tune', 'fastdecode', 'F:\\Elgato Media\\Tom Clancys', 'Rainbow', 'Six', 'SiegeBL_proxyTom', 'Clancys Rainbow Six  Siege 2019.10.22 - 11.15.51.01.mp4\\proxy_25.avi']
DEBUG:BPS:CALL :: ['ffmpeg', '-hwaccel', 'auto', '-y', '-v', 'quiet', '-stats', '-i', 'F:\\Elgato Media\\Tom Clancys', 'Rainbow', 'Six', 'SiegeTom', 'Clancys Rainbow Six  Siege 2019.10.22 - 11.30.41.03.DVR.mp4', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=ceil(iw*0.25/2)*2:ceil(ih*0.25/2)*2', '-c:v', 'libx264', '-crf', '25', '-preset', 'faster', '-tune', 'fastdecode', 'F:\\Elgato Media\\Tom Clancys', 'Rainbow', 'Six', 'SiegeBL_proxyTom', 'Clancys Rainbow Six  Siege 2019.10.22 - 11.30.41.03.DVR.mp4\\proxy_25.avi']
DEBUG:BPS:CALL :: ['ffmpeg', '-hwaccel', 'auto', '-y', '-v', 'quiet', '-stats', '-i', 'F:\\Elgato Media\\Tom Clancys', 'Rainbow', 'Six', 'SiegeTom', 'Clancys Rainbow Six  Siege 2019.10.22 - 11.41.04.04.DVR.mp4', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=ceil(iw*0.25/2)*2:ceil(ih*0.25/2)*2', '-c:v', 'libx264', '-crf', '25', '-preset', 'faster', '-tune', 'fastdecode', 'F:\\Elgato Media\\Tom Clancys', 'Rainbow', 'Six', 'SiegeBL_proxyTom', 'Clancys Rainbow Six  Siege 2019.10.22 - 11.41.04.04.DVR.mp4\\proxy_25.avi']
  0%|                                                                                                                                                                                                     | 0/4 [00:00<?, ?files/s]Traceback (most recent call last):
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cubuzz\AppData\Local\Programs\Python\Python38-32\Scripts\bpsproxy.exe\__main__.py", line 9, in <module>
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\site-packages\bpsproxy\__main__.py", line 157, in main
    call(C, clargs, cmds=cmds, **kwargs)
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\site-packages\bpsproxy\call.py", line 95, in call
    return [p.stdout for p in ps]
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\site-packages\bpsproxy\call.py", line 95, in <listcomp>
    return [p.stdout for p in ps]
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\site-packages\bpsproxy\call.py", line 91, in <lambda>
    map(lambda cmd: sp.run(cmd[1], **kwargs_s), cmds[1]),
  File "c:\users\cubuzz\appdata\local\programs\python\python38-32\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-hwaccel', 'auto', '-y', '-v', 'quiet', '-stats', '-i', 'F:\\Elgato Media\\Tom Clancys', 'Rainbow', 'Six', 'SiegeTom', 'Clancys Rainbow Six  Siege 2019.10.21 - 21.08.20.01.mp4', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=ceil(iw*0.25/2)*2:ceil(ih*0.25/2)*2', '-c:v', 'libx264', '-crf', '25', '-preset', 'faster', '-tune', 'fastdecode', 'F:\\Elgato Media\\Tom Clancys', 'Rainbow', 'Six', 'SiegeBL_proxyTom', 'Clancys Rainbow Six  Siege 2019.10.21 - 21.08.20.01.mp4\\proxy_25.avi']' returned non-zero exit status 1.
  0%|                                                                                                                                                                                                     | 0/4 [00:00<?, ?files/s]
```

**Comment by NathanLovato** [comment]
There's an issue with the file path. You can fix it by changing the name of the video files. In general, spaces in names and special characters can cause unexpected issues with command line programs.

**Comment by amiramitai** [comment]
I'm getting the same issue. For me, the problem was that some shells parse the Asterisk '*' differently. To make the scale argument work, add quotation arount it, like this:
from:
scale=ceil(iw*0.25/2)*2:ceil(ih*0.25/2)*2
to:
scale="ceil(iw*0.25/2)*2:ceil(ih*0.25/2)*2"

**Comment by NathanLovato** [comment]
You need to use single quotes for string literals: '...*...'. This should work on most shells. Otherwise, yes, it'll treat the * as "all files in this folder"
